// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJLXEKlsuTmYjELAw7ysg-Z5AMn72F4v0',
    appId: '1:153838541528:web:eb5cf3d034ef98864c55ad',
    messagingSenderId: '153838541528',
    projectId: 'mireles-99c30',
    authDomain: 'mireles-99c30.firebaseapp.com',
    storageBucket: 'mireles-99c30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1lPJVMCB-S9eo0E7Nu4emDJP1BIS1pfQ',
    appId: '1:153838541528:android:bf7adf43780bbe424c55ad',
    messagingSenderId: '153838541528',
    projectId: 'mireles-99c30',
    storageBucket: 'mireles-99c30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdGPYrNLXt_FNpnkgNQILHBuM2hRHOuRc',
    appId: '1:153838541528:ios:a606323f906d068d4c55ad',
    messagingSenderId: '153838541528',
    projectId: 'mireles-99c30',
    storageBucket: 'mireles-99c30.appspot.com',
    iosBundleId: 'com.example.empty',
  );

}